//aca listo los productos como array de objetos
//se recorre el array para listar los productos en html
const productos = [
    {
        id: 1,
        productName: "The Psychology of Money",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 100,
        quantity: 1,
        img: "/img/libro1.jpg",
    },
    {
        id: 2,
        productName: "How Innovation Works",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 150,
        quantity: 1,
        img: "/img/libro2.jpg",
    },
    {
        id: 3,
        productName: "Misticos, Cientificos y Otros Bipedos",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 200,
        quantity: 1,
        img: "/img/libro3.jpg",
    },
    {
        id: 4,
        productName: "Design UX for SaaS",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 200,
        quantity: 1,
        img: "/img/libro4.jpg",
    },
    {
        id: 5,
        productName: "A Primer on Data Drift",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 200,
        quantity: 1,
        img: "/img/libro5.jpg",
    },
    {
        id: 6,
        productName: "Formas Breves",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 200,
        quantity: 1,
        img: "/img/libro6.jpg",
    },
    {
        id: 7,
        productName: "Design & Build Your Product Simultaneously",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 200,
        quantity: 1,
        img: "/img/libro7.png",
    },
    {
        id: 8,
        productName: "The Innovator's Dilemma",
        description:  "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 200,
        quantity: 1,
        img: "/img/libro8.jpg",
    },
];