//aca listo los productos como array de objetos
//se recorre el array para listar los productos en html
const productos = [
    {
        id: 1,
        title: "The Psychology of Money",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 100,
        quantity: 1,
        img: "/client/img/libro1.jpg",
    },
    {
        id: 2,
        title: "How Innovation Works",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 300,
        quantity: 1,
        img: "/client/img/libro2.jpg",
    },
    {
        id: 3,
        title: "Misticos, Cientificos y Otros Bipedos",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 200,
        quantity: 1,
        img: "/client/img/libro3.jpg",
    },
    {
        id: 4,
        title: "Design UX for SaaS",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 400,
        quantity: 1,
        img: "/client/img/libro4.jpg",
    },
    {
        id: 5,
        title: "A Primer on Data Drift",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 200,
        quantity: 1,
        img: "/client/img/libro5.jpg",
    },
    {
        id: 6,
        title: "Formas Breves",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 600,
        quantity: 1,
        img: "/client/img/libro6.jpg",
    },
    {
        id: 7,
        title: "Design & Build Your Product Simultaneously",
        description: "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 100,
        quantity: 1,
        img: "/client/img/libro7.png",
    },
    {
        id: 8,
        title: "The Innovator's Dilemma",
        description:  "Es un libro que explica cómo la psicología influye en nuestro comportamiento y éxito financiero, y cómo podemos aprender a manejar mejor el dinero para lograr nuestros objetivos y ser más felices.",
        price: 200,
        quantity: 1,
        img: "/client/img/libro8.jpg",
    },
];